MIT-LCP/lcp-website

- templates/about.html
Removes Ken's contact information from the website.
> Removes Ken's info

- templates/index.html
Adjusts home page to include the research summary. The order of the page, from top to bottom, is now: welcome banner, research summary, news items.
> Adjust Home page

- config.py
- config/dev/.env.example
- config/production/.env.example
- main.py
Cleanup to remove the dashboard.
> Dashboard removal

- main.py
Re adding news since I removed it by mistake.
> re-add news removed by mistake on 3abf1d4

- requirements.txt
I am removing old requirements installations since they are not needed because there is no more dashboard.
> update requirements with prior commit dashboard removal

- config.py
- config/dev/.env.example
- config/production/.env.example
I am removing un-needed variables from the environment/config files.
> remove unneeded variable from env

- deploy/etc/uwsgi.d/wsgi_lcp.ini
- main.py
Here I remove the custom log config and separate it at a WSGI level.
> Altered logger destination format

- config/staging/.env.example
- deploy/etc/nginx/sites_enabled/breadboard_nginx.conf
- deploy/etc/uwsgi.d/lcp_development_breadboard.ini
- main.py
Here I am adding the running NGINX config from breadboard since
the staging live is running there under /lcp_dev.
I am also adding the staging .env.example.
Adding the running uwsgi config
And I modified the main.py to add the application root to all the
routes assuming the .env from staging is being used.
> Adding staging info

- deploy/etc/uwsgi.d/lcp_development_breadboard.ini
- deploy/etc/uwsgi.d/wsgi_lcp.ini
- deploy/var/www/vhosts/breadboard-lcp.mit.edu/Flask/wsgi.py
Modifies the uwsgi configuration to use the correct references to the necessary files for deploying.
> Modifies uwsgi configuration

- templates/about.html
- templates/mimic.html
- templates/people.html
- templates/physionet.html
This adds a couple of minor changes to pass validation on https://validator.w3.org/nu/:
- Change "name" to "id" (the name attribute is obsolete)
- change `"width="120px"` to `width="120"` on people page.
> Couple of minor changes for w3c validation

- templates/navbar.html
Modifies the top `navbar` so that it wraps when the window width is decreased significantly. Fixes part of #60.
> Adds wrap to navbar #60

- templates/about.html
Updates the address used on the About page from Carleton street to Mass ave.
> Updates About page address

- templates/about.html
- templates/footer.html
Adds E25-505 to address to specify the LCP. Fixes part of #60.
> Adds E25-505 to address #60

- templates/mimic.html
- templates/physionet.html
Adds links to PhysioNet and MIMIC on their respective pages. Fixes part of #60.
> Adds PhysioNet and MIMIC links #60

- templates/about.html
- templates/footer.html
Adds LCP to address to clarify it more and have it match the old website.
> Changes address

- templates/about.html
Changes contact information to remove e-mail addresses and phone numbers while instead adding MIT extension.
> Changes contact information

- templates/footer.html
Removes all footer content except for the accessibility link which is now placed directly below the logos.
> Removes footer content

- sitedata/news.yml
Adds the most recent news item pertaining an award received at the AMIA 2020 Annual Symposium by one of the LCP students and research scientists.
> Adds new news item

- deploy/etc/uwsgi.d/wsgi_lcp.ini
Here I set the plugin path for the uwsgi python3 module.
> Set proper uwsgi python plugin

- scripts/change.py
This change updates the paths in `change.py` to reflect the new structure of the repo.
> Updates the paths in change.py
