MIT-LCP/lcp-website

templates/footer.html

Couple of very minor changes in the footer:
- Left aligns the "Contact" header with the content of the column
- Fixes the mailto: link so that it validates on the W3C checker (removes a space).
- Changes "Official GitHub page" to "GitHub"

Align the "contact" header with the text below

---

config.py

Before this, the env variables were all set to default.
Now we are actually reading the variables from the .env file.
This read is done in the import dont at the Postgres.py file.
If the file is removed, then we have to add the import to main.py

This makes flask to read the dotenv file

---

templates/about.html
templates/mimic.html
templates/news.html
templates/people.html
templates/physionet.html

The site should not raise errors or warnings when run through https://validator.w3.org/
This fixes the remaining issues on all pages except the publications page (/publications). I'm not entirely sure how this content is generated, so left that for now.
- replace name tag with the id tag for internal links
- set the images on the people page to a fix pixel width (rather than %)
- remove the unnecessary `role="main"` from the news page

Minor fixes for W3C validation

---

Makefile
sitedata-changed.sh

We would like to provide a simple(ish) way for people to update content on the website (e.g. people, news, publications). 
This makefile attempts to do that by adding a recipe that checks for changes in the sitedata folder and then (1) commits the change to github and (2) pushes the change to our servers.
Some notes:
- `make help` prints a list of available commands.
- `make run` activates a virtual environment (note that it requires a file called `activate`) and then runs the site locally.
- `make update` checks whether sitedata has been updated by calling the `sitedata-changed.sh` script. If so, it:
- Commits the change to local branches (dev and production).
- Pushes the change to github (commented out for now)
- Pushes the change to our servers (not yet implemented).
I'm not convinced …

Adds draft makefile for making site updates

---

static/css/custom.css

Fixes the image background gradient on the home page to more resemble the color of the logo in the top left corner. Changes the gradient to start at 100% opacity instead of 90%. Fixes part of #60.

Fixes image background gradient #60

---

templates/footer.html

Changes the address used to contact the lab from the private address to the public MIT mailing address. Fixes part of #60.

Changes contact address #60

---

static/css/custom.css
templates/navbar.html

Adds a background to the LCP logo on the main page. This revives the appearance of the logo on the old website. Also fixes the image size to maintain size during adjustment of the window. Fixes part of #60.

Adds background to logo #60.

---

templates/index.html

Fixes the research summary paragraph on the main page to split multiple paragraphes by `<p>` tags instead of `<br>` tags. Fixes part of #60.

Fixes main page intro paragraph #60

---

static/css/custom.css

Reduces the `font-weight` of the titles in the footer from 700 to 500 to match the other headers. Fixes part of #60.

Reduces footer title boldness #60

---

templates/people.html

Fixes the `h2` tag of the lab members name to an `h3` tag to stay consistent with the rest of the header tags. Fixes part of #60.

Fixes People Page header ordering #60.

---

main.py
templates/people.html

Changes the photos on the People Page to include a more descriptive alt tag: Roger Mark to photo of Roger Mark. Also changes photo id to be more descriptive: Roger_Mark to photo_of_Roger_Mark. Fixes part of #60.

People Page: change photo alt and id #60

---

change.py
publications.html
static/css/custom.css
templates/about.html
templates/header.html
templates/index.html
templates/mimic.html
templates/news.html
templates/people.html
templates/physionet.html
templates/publications.html

Adds links at the top of each page to skip users directly to the content. This is useful for those using Lynx and Screen Readers as mentioned in #60. Fixes part of #60.

Adds skip to content links #60.

---

templates/base.html
templates/header.html

Fixes the error where the `skip-to-content` link was inserted before the valid HTML began which cause W3C errors. Now, the link is inserted immeditally after the start of the body tag. Fixes part of #60.

Fixes skip-to-content error #60

---

main.py
templates/index.html
templates/news.html
templates/news_post.html

Automatically generates a new page for each news item. This means that the `continue reading` link on the home page now correctly links to an expanded form of the news item presented on the home page. Further, adds some error protection on the actual news page by allowing the external URL link to be optional. Fixes part of #60.

Generates new page for each news item #60

---

Makefile

Adds the ability to update publications using the `Makefile`. By running `make publications`, the user runs the `change.py` script and then runs `make update` which updates the changes to Github. For now, the `make update` section is commented out until development is finished so accidental changes don't get pushed to Github.

Adds make publications

---

deploy/post-receive

Adds `post-receive` file to the repository as taken from the server. Basic overview:
1. A `push` is received to the repository from anywhere (typically a local clone for this case)
2. The contents of the new `push` are checked-out 
3. The Flask app is restarted by restarting its specific UWSGI configuration

Adds post-receive

---

templates/index.html

Removes the research summary from the Home page since it is repeated text from the About page.

Removes research summary

---

templates/about.html

Removes the indentation for the contact information on the About page. This makes it more in-line and consistent with the style used on the rest of the page.

Removes contact info indent

---

main.py
templates/navbar.html

The default URL for the homepage is: https://lcp.mit.edu/index.html. `/home` would be friendlier and consistent with the URLs for other pages (e.g. https://lcp.mit.edu/about, https://lcp.mit.edu/people, etc).
This is a minor change to switch the homepage to https://lcp.mit.edu/home. `index.html` will continue to render the homepage for now, but it could be redirected to `/home` later.

use /home instead of /index.html for homepage

---

deploy/etc/uwsgi.d/wsgi_lcp.ini
scripts/config.py

There was a 502 error in which the env variables are loaded all as strings. Here we add the lists as lists.

Evaluates variables as list not as strings

---

deploy/post-receive

All the logs are located in /var/log/ and the '/data' was not intended for logs in this server. 
Also, the live version of this file uses the '/var' not the '/data'.

Alter log location

---

static/css/custom.css

This change reverts back to the default link color pre-Boostrap and also changes the default body font to Helvetica Neue, Arial, sans-serif to increase readability.

Reverts to default link color and Helvetica font
